// "use client"
import "@/styles/globals.css";
import {inter, montserrat, poppins, raleway} from "@/lib/fonts";
import {cn} from "@/lib/utils";
import Banner from "@/public/real-estate-banner.png";
import Image from "next/image";
import React from "react";
import Logo from "@/public/Logo.svg";

export const metadata = {
    title: "Spaces App",
    description: "Generated by create next app",
};

export default function AuthLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <div
            className={cn(
                "h-screen max-w-screen  bg-background text-slate-900 antialiased",
                poppins.variable,
                inter.variable,
                montserrat.variable,
                raleway.variable
            )}>
            {/*<Navbar/>*/}
            <section className="relative flex flex-wrap lg:h-screen lg:items-center">
                <div className="relative hidden md:block md:w-1/3 lg:w-1/2 h-screen ">
                    <Image
                        src={Banner}
                        alt="Banner"
                        priority
                        className="absolute inset-0 h-full w-full object-cover"
                    />
                </div>

                <div
                    className="w-full md:w-2/3 lg:w-1/2  px-0 h-screen py-0 sm:px-6 sm:py-16 lg:px-8 lg:py-8 flex flex-col overflow-y-scroll ">
                    <div
                        className={
                            "px-4 lg:container max-w-[500px] w-[90%] mx-auto h-fit my-auto"
                        }>
                        <div>
                            <Image
                                src={Logo}
                                alt="Logo"
                                className={"h-auto w-[300px] mx-auto my-2"}
                            />
                        </div>
                        <div className={"xs:mx-6 lg:mx-12 "}>
                            {children}
                        </div>
                    </div>
                </div>
            </section>
        </div>
    );
}
