import "@/styles/globals.css";
import { inter, montserrat, poppins, raleway } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";
// import {Toaster} from "@/ui/toaster";

import Image from "next/image";
import Logo from "@/public/Logo.svg";
import Hero from "@/public/hero-image.png";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
export const metadata = {
  title: "Spaces App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode;}) {
  return (
    <>
      <html
        lang="en"
        className={cn(
          "min-h-screen bg-background text-slate-900 antialiased",
          poppins.variable,
          inter.variable,
          montserrat.variable,
          raleway.variable
        )}
      >
        <body className={cn("min-h-screen antialiased")}>
          <main className="">
            {children}
            <Toaster position="top-center" reverseOrder={false} />
          </main>
        </body>
      </html>
    </>
  );
}
